# Generated by Django 3.2.7 on 2021-09-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='static/img/student_img.png', null=True, upload_to='media/'),
        ),
    ]
