# Generated by Django 3.2.7 on 2021-09-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='telephone',
            new_name='phone',
        ),
    ]
