# Generated by Django 3.2.7 on 2021-09-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_telephone_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='static/img/teacher_img.png', null=True, upload_to='media/'),
        ),
    ]
