# Generated by Django 3.2.7 on 2021-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='fb_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
