# Generated by Django 3.2.7 on 2021-09-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0003_alter_teacher_image'),
        ('students', '0003_alter_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ManyToManyField(related_name='student_courses', to='students.Student')),
                ('teacher', models.ManyToManyField(related_name='teacher_courses', to='teachers.Teacher')),
            ],
        ),
    ]
