# Generated by Django 3.2.7 on 2021-09-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210914_1443'),
        ('courses', '0006_lesson_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ManyToManyField(related_name='student', to='students.Student'),
        ),
    ]
