# Generated by Django 3.2.7 on 2021-09-19 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_attendance_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='course_name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
