# Generated by Django 3.2.7 on 2021-09-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_attendance_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
