# Generated by Django 3.2.7 on 2021-09-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_attendance_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='end_time',
        ),
    ]
