# Generated by Django 3.2.7 on 2021-09-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_lesson_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
