# Generated by Django 3.2.7 on 2021-09-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_lesson_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
